name: ecommerce_concept
description: "Flutter challenge for cashea"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  async: ^2.11.0
  google_fonts: ^6.2.1
  go_router: ^14.2.0
  responsive_framework: ^1.4.0
  iconsax_flutter: ^1.0.0
  super_tooltip: ^2.0.8
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  equatable: ^2.0.5
  dio: ^5.7.0
  json_annotation: ^4.9.0
  talker_dio_logger: ^4.4.1
  talker: ^4.4.1
  formz: ^0.7.0
  talker_bloc_logger: ^4.4.1
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
